//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyClient.ReservationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", ConfigurationName="ReservationService.LabProxySoap")]
    public interface LabProxySoap {
        
        // CODEGEN: Generating message contract since element name passkey from namespace http://ilab.mit.edu/iLabs/Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/GetReservationInfo", ReplyAction="*")]
        ProxyClient.ReservationService.GetReservationInfoResponse GetReservationInfo(ProxyClient.ReservationService.GetReservationInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReservationInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReservationInfo", Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public ProxyClient.ReservationService.GetReservationInfoRequestBody Body;
        
        public GetReservationInfoRequest() {
        }
        
        public GetReservationInfoRequest(ProxyClient.ReservationService.GetReservationInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ilab.mit.edu/iLabs/Services")]
    public partial class GetReservationInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string passkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string labServerTime;
        
        public GetReservationInfoRequestBody() {
        }
        
        public GetReservationInfoRequestBody(string passkey, string labServerTime) {
            this.passkey = passkey;
            this.labServerTime = labServerTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReservationInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReservationInfoResponse", Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public ProxyClient.ReservationService.GetReservationInfoResponseBody Body;
        
        public GetReservationInfoResponse() {
        }
        
        public GetReservationInfoResponse(ProxyClient.ReservationService.GetReservationInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ilab.mit.edu/iLabs/Services")]
    public partial class GetReservationInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetReservationInfoResult;
        
        public GetReservationInfoResponseBody() {
        }
        
        public GetReservationInfoResponseBody(string GetReservationInfoResult) {
            this.GetReservationInfoResult = GetReservationInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LabProxySoapChannel : ProxyClient.ReservationService.LabProxySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LabProxySoapClient : System.ServiceModel.ClientBase<ProxyClient.ReservationService.LabProxySoap>, ProxyClient.ReservationService.LabProxySoap {
        
        public LabProxySoapClient() {
        }
        
        public LabProxySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabProxySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabProxySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabProxySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.GetReservationInfoResponse ProxyClient.ReservationService.LabProxySoap.GetReservationInfo(ProxyClient.ReservationService.GetReservationInfoRequest request) {
            return base.Channel.GetReservationInfo(request);
        }
        
        public string GetReservationInfo(string passkey, string labServerTime) {
            ProxyClient.ReservationService.GetReservationInfoRequest inValue = new ProxyClient.ReservationService.GetReservationInfoRequest();
            inValue.Body = new ProxyClient.ReservationService.GetReservationInfoRequestBody();
            inValue.Body.passkey = passkey;
            inValue.Body.labServerTime = labServerTime;
            ProxyClient.ReservationService.GetReservationInfoResponse retVal = ((ProxyClient.ReservationService.LabProxySoap)(this)).GetReservationInfo(inValue);
            return retVal.Body.GetReservationInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", ConfigurationName="ReservationService.IProcessAgent")]
    public interface IProcessAgent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/GetServiceTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.DateTime GetServiceTime();
        
        // CODEGEN: Generating message contract since message part namespace (http://ilab.mit.edu/iLabs/type) does not match the default value (http://ilab.mit.edu/iLabs/Services)
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/GetStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.GetStatusResponse GetStatus(ProxyClient.ReservationService.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since message StatusNotificationRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/StatusNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.StatusNotificationResponse StatusNotification(ProxyClient.ReservationService.StatusNotificationRequest request);
        
        // CODEGEN: Generating message contract since message CancelTicketRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/CancelTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.CancelTicketResponse CancelTicket(ProxyClient.ReservationService.CancelTicketRequest request);
        
        // CODEGEN: Generating message contract since message InstallDomainCredentialsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/InstallDomainCredentials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.InstallDomainCredentialsResponse InstallDomainCredentials(ProxyClient.ReservationService.InstallDomainCredentialsRequest request);
        
        // CODEGEN: Generating message contract since message ModifyDomainCredentialsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/ModifyDomainCredentials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.ModifyDomainCredentialsResponse ModifyDomainCredentials(ProxyClient.ReservationService.ModifyDomainCredentialsRequest request);
        
        // CODEGEN: Generating message contract since message RemoveDomainCredentialsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/RemoveDomainCredentials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.RemoveDomainCredentialsResponse RemoveDomainCredentials(ProxyClient.ReservationService.RemoveDomainCredentialsRequest request);
        
        // CODEGEN: Generating message contract since message ModifyProcessAgentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/ModifyProcessAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.ModifyProcessAgentResponse ModifyProcessAgent(ProxyClient.ReservationService.ModifyProcessAgentRequest request);
        
        // CODEGEN: Generating message contract since message RetireProcessAgentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/RetireProcessAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.RetireProcessAgentResponse RetireProcessAgent(ProxyClient.ReservationService.RetireProcessAgentRequest request);
        
        // CODEGEN: Generating message contract since message RegisterRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://ilab.mit.edu/iLabs/Services/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationHeader))]
        ProxyClient.ReservationService.RegisterResponse Register(ProxyClient.ReservationService.RegisterRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class StatusReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool onlineField;
        
        private string serviceGuidField;
        
        private string payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool online {
            get {
                return this.onlineField;
            }
            set {
                this.onlineField = value;
                this.RaisePropertyChanged("online");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serviceGuid {
            get {
                return this.serviceGuidField;
            }
            set {
                this.serviceGuidField = value;
                this.RaisePropertyChanged("serviceGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class ServiceDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceProviderInfoField;
        
        private Coupon couponField;
        
        private string consumerInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string serviceProviderInfo {
            get {
                return this.serviceProviderInfoField;
            }
            set {
                this.serviceProviderInfoField = value;
                this.RaisePropertyChanged("serviceProviderInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Coupon coupon {
            get {
                return this.couponField;
            }
            set {
                this.couponField = value;
                this.RaisePropertyChanged("coupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string consumerInfo {
            get {
                return this.consumerInfoField;
            }
            set {
                this.consumerInfoField = value;
                this.RaisePropertyChanged("consumerInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class Coupon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long couponIdField;
        
        private string issuerGuidField;
        
        private string passkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long couponId {
            get {
                return this.couponIdField;
            }
            set {
                this.couponIdField = value;
                this.RaisePropertyChanged("couponId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string issuerGuid {
            get {
                return this.issuerGuidField;
            }
            set {
                this.issuerGuidField = value;
                this.RaisePropertyChanged("issuerGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string passkey {
            get {
                return this.passkeyField;
            }
            set {
                this.passkeyField = value;
                this.RaisePropertyChanged("passkey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class InitAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string initPasskeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string initPasskey {
            get {
                return this.initPasskeyField;
            }
            set {
                this.initPasskeyField = value;
                this.RaisePropertyChanged("initPasskey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class ProcessAgent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agentGuidField;
        
        private string agentNameField;
        
        private string typeField;
        
        private string domainGuidField;
        
        private string codeBaseUrlField;
        
        private string webServiceUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string agentGuid {
            get {
                return this.agentGuidField;
            }
            set {
                this.agentGuidField = value;
                this.RaisePropertyChanged("agentGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string agentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
                this.RaisePropertyChanged("agentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string domainGuid {
            get {
                return this.domainGuidField;
            }
            set {
                this.domainGuidField = value;
                this.RaisePropertyChanged("domainGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codeBaseUrl {
            get {
                return this.codeBaseUrlField;
            }
            set {
                this.codeBaseUrlField = value;
                this.RaisePropertyChanged("codeBaseUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string webServiceUrl {
            get {
                return this.webServiceUrlField;
            }
            set {
                this.webServiceUrlField = value;
                this.RaisePropertyChanged("webServiceUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgentAuthHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Coupon couponField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Coupon coupon {
            get {
                return this.couponField;
            }
            set {
                this.couponField = value;
                this.RaisePropertyChanged("coupon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class AgentAuthHeader : AuthenticationHeader {
        
        private string agentGuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string agentGuid {
            get {
                return this.agentGuidField;
            }
            set {
                this.agentGuidField = value;
                this.RaisePropertyChanged("agentGuid");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class StatusNotificationReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int alertCodeField;
        
        private string serviceGuidField;
        
        private System.DateTime timeField;
        
        private string payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int alertCode {
            get {
                return this.alertCodeField;
            }
            set {
                this.alertCodeField = value;
                this.RaisePropertyChanged("alertCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serviceGuid {
            get {
                return this.serviceGuidField;
            }
            set {
                this.serviceGuidField = value;
                this.RaisePropertyChanged("serviceGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        public GetStatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.StatusReport GetStatusResult;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(ProxyClient.ReservationService.StatusReport GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusNotification", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class StatusNotificationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.StatusNotificationReport report;
        
        public StatusNotificationRequest() {
        }
        
        public StatusNotificationRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, ProxyClient.ReservationService.StatusNotificationReport report) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.report = report;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StatusNotificationResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class StatusNotificationResponse {
        
        public StatusNotificationResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelTicket", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class CancelTicketRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.Coupon coupon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=1)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=2)]
        public string redeemer;
        
        public CancelTicketRequest() {
        }
        
        public CancelTicketRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, ProxyClient.ReservationService.Coupon coupon, string type, string redeemer) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.coupon = coupon;
            this.type = type;
            this.redeemer = redeemer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelTicketResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class CancelTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public bool CancelTicketResult;
        
        public CancelTicketResponse() {
        }
        
        public CancelTicketResponse(bool CancelTicketResult) {
            this.CancelTicketResult = CancelTicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstallDomainCredentials", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class InstallDomainCredentialsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.InitAuthHeader InitAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.ProcessAgent service;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.Coupon inIdentCoupon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.Coupon outIdentCoupon;
        
        public InstallDomainCredentialsRequest() {
        }
        
        public InstallDomainCredentialsRequest(ProxyClient.ReservationService.InitAuthHeader InitAuthHeader, ProxyClient.ReservationService.ProcessAgent service, ProxyClient.ReservationService.Coupon inIdentCoupon, ProxyClient.ReservationService.Coupon outIdentCoupon) {
            this.InitAuthHeader = InitAuthHeader;
            this.service = service;
            this.inIdentCoupon = inIdentCoupon;
            this.outIdentCoupon = outIdentCoupon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InstallDomainCredentialsResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class InstallDomainCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.ProcessAgent InstallDomainCredentialsResult;
        
        public InstallDomainCredentialsResponse() {
        }
        
        public InstallDomainCredentialsResponse(ProxyClient.ReservationService.ProcessAgent InstallDomainCredentialsResult) {
            this.InstallDomainCredentialsResult = InstallDomainCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyDomainCredentials", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class ModifyDomainCredentialsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public string originalGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.ProcessAgent agent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=2)]
        public string extra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.Coupon inCoupon;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.Coupon outCoupon;
        
        public ModifyDomainCredentialsRequest() {
        }
        
        public ModifyDomainCredentialsRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string originalGuid, ProxyClient.ReservationService.ProcessAgent agent, string extra, ProxyClient.ReservationService.Coupon inCoupon, ProxyClient.ReservationService.Coupon outCoupon) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.originalGuid = originalGuid;
            this.agent = agent;
            this.extra = extra;
            this.inCoupon = inCoupon;
            this.outCoupon = outCoupon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyDomainCredentialsResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class ModifyDomainCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public int ModifyDomainCredentialsResult;
        
        public ModifyDomainCredentialsResponse() {
        }
        
        public ModifyDomainCredentialsResponse(int ModifyDomainCredentialsResult) {
            this.ModifyDomainCredentialsResult = ModifyDomainCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDomainCredentials", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class RemoveDomainCredentialsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public string domainGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=1)]
        public string serviceGuid;
        
        public RemoveDomainCredentialsRequest() {
        }
        
        public RemoveDomainCredentialsRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string domainGuid, string serviceGuid) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.domainGuid = domainGuid;
            this.serviceGuid = serviceGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveDomainCredentialsResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class RemoveDomainCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public int RemoveDomainCredentialsResult;
        
        public RemoveDomainCredentialsResponse() {
        }
        
        public RemoveDomainCredentialsResponse(int RemoveDomainCredentialsResult) {
            this.RemoveDomainCredentialsResult = RemoveDomainCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyProcessAgent", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class ModifyProcessAgentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public string originalGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/type", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProxyClient.ReservationService.ProcessAgent agent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=2)]
        public string extra;
        
        public ModifyProcessAgentRequest() {
        }
        
        public ModifyProcessAgentRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string originalGuid, ProxyClient.ReservationService.ProcessAgent agent, string extra) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.originalGuid = originalGuid;
            this.agent = agent;
            this.extra = extra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyProcessAgentResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class ModifyProcessAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public int ModifyProcessAgentResult;
        
        public ModifyProcessAgentResponse() {
        }
        
        public ModifyProcessAgentResponse(int ModifyProcessAgentResult) {
            this.ModifyProcessAgentResult = ModifyProcessAgentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetireProcessAgent", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class RetireProcessAgentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public string domainGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=1)]
        public string serviceGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=2)]
        public bool state;
        
        public RetireProcessAgentRequest() {
        }
        
        public RetireProcessAgentRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string domainGuid, string serviceGuid, bool state) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.domainGuid = domainGuid;
            this.serviceGuid = serviceGuid;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetireProcessAgentResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class RetireProcessAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public int RetireProcessAgentResult;
        
        public RetireProcessAgentResponse() {
        }
        
        public RetireProcessAgentResponse(int RetireProcessAgentResult) {
            this.RetireProcessAgentResult = RetireProcessAgentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Register", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
        public ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=0)]
        public string registerGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ilab.mit.edu/iLabs/Services", Order=1)]
        public ServiceDescription[] info;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string registerGuid, ServiceDescription[] info) {
            this.AgentAuthHeader = AgentAuthHeader;
            this.registerGuid = registerGuid;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterResponse", WrapperNamespace="http://ilab.mit.edu/iLabs/Services", IsWrapped=true)]
    public partial class RegisterResponse {
        
        public RegisterResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProcessAgentChannel : ProxyClient.ReservationService.IProcessAgent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProcessAgentClient : System.ServiceModel.ClientBase<ProxyClient.ReservationService.IProcessAgent>, ProxyClient.ReservationService.IProcessAgent {
        
        public ProcessAgentClient() {
        }
        
        public ProcessAgentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessAgentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessAgentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessAgentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetServiceTime() {
            return base.Channel.GetServiceTime();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.GetStatusResponse ProxyClient.ReservationService.IProcessAgent.GetStatus(ProxyClient.ReservationService.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public ProxyClient.ReservationService.StatusReport GetStatus() {
            ProxyClient.ReservationService.GetStatusRequest inValue = new ProxyClient.ReservationService.GetStatusRequest();
            ProxyClient.ReservationService.GetStatusResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).GetStatus(inValue);
            return retVal.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.StatusNotificationResponse ProxyClient.ReservationService.IProcessAgent.StatusNotification(ProxyClient.ReservationService.StatusNotificationRequest request) {
            return base.Channel.StatusNotification(request);
        }
        
        public void StatusNotification(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, ProxyClient.ReservationService.StatusNotificationReport report) {
            ProxyClient.ReservationService.StatusNotificationRequest inValue = new ProxyClient.ReservationService.StatusNotificationRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.report = report;
            ProxyClient.ReservationService.StatusNotificationResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).StatusNotification(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.CancelTicketResponse ProxyClient.ReservationService.IProcessAgent.CancelTicket(ProxyClient.ReservationService.CancelTicketRequest request) {
            return base.Channel.CancelTicket(request);
        }
        
        public bool CancelTicket(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, ProxyClient.ReservationService.Coupon coupon, string type, string redeemer) {
            ProxyClient.ReservationService.CancelTicketRequest inValue = new ProxyClient.ReservationService.CancelTicketRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.coupon = coupon;
            inValue.type = type;
            inValue.redeemer = redeemer;
            ProxyClient.ReservationService.CancelTicketResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).CancelTicket(inValue);
            return retVal.CancelTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.InstallDomainCredentialsResponse ProxyClient.ReservationService.IProcessAgent.InstallDomainCredentials(ProxyClient.ReservationService.InstallDomainCredentialsRequest request) {
            return base.Channel.InstallDomainCredentials(request);
        }
        
        public ProxyClient.ReservationService.ProcessAgent InstallDomainCredentials(ProxyClient.ReservationService.InitAuthHeader InitAuthHeader, ProxyClient.ReservationService.ProcessAgent service, ProxyClient.ReservationService.Coupon inIdentCoupon, ProxyClient.ReservationService.Coupon outIdentCoupon) {
            ProxyClient.ReservationService.InstallDomainCredentialsRequest inValue = new ProxyClient.ReservationService.InstallDomainCredentialsRequest();
            inValue.InitAuthHeader = InitAuthHeader;
            inValue.service = service;
            inValue.inIdentCoupon = inIdentCoupon;
            inValue.outIdentCoupon = outIdentCoupon;
            ProxyClient.ReservationService.InstallDomainCredentialsResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).InstallDomainCredentials(inValue);
            return retVal.InstallDomainCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.ModifyDomainCredentialsResponse ProxyClient.ReservationService.IProcessAgent.ModifyDomainCredentials(ProxyClient.ReservationService.ModifyDomainCredentialsRequest request) {
            return base.Channel.ModifyDomainCredentials(request);
        }
        
        public int ModifyDomainCredentials(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string originalGuid, ProxyClient.ReservationService.ProcessAgent agent, string extra, ProxyClient.ReservationService.Coupon inCoupon, ProxyClient.ReservationService.Coupon outCoupon) {
            ProxyClient.ReservationService.ModifyDomainCredentialsRequest inValue = new ProxyClient.ReservationService.ModifyDomainCredentialsRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.originalGuid = originalGuid;
            inValue.agent = agent;
            inValue.extra = extra;
            inValue.inCoupon = inCoupon;
            inValue.outCoupon = outCoupon;
            ProxyClient.ReservationService.ModifyDomainCredentialsResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).ModifyDomainCredentials(inValue);
            return retVal.ModifyDomainCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.RemoveDomainCredentialsResponse ProxyClient.ReservationService.IProcessAgent.RemoveDomainCredentials(ProxyClient.ReservationService.RemoveDomainCredentialsRequest request) {
            return base.Channel.RemoveDomainCredentials(request);
        }
        
        public int RemoveDomainCredentials(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string domainGuid, string serviceGuid) {
            ProxyClient.ReservationService.RemoveDomainCredentialsRequest inValue = new ProxyClient.ReservationService.RemoveDomainCredentialsRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.domainGuid = domainGuid;
            inValue.serviceGuid = serviceGuid;
            ProxyClient.ReservationService.RemoveDomainCredentialsResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).RemoveDomainCredentials(inValue);
            return retVal.RemoveDomainCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.ModifyProcessAgentResponse ProxyClient.ReservationService.IProcessAgent.ModifyProcessAgent(ProxyClient.ReservationService.ModifyProcessAgentRequest request) {
            return base.Channel.ModifyProcessAgent(request);
        }
        
        public int ModifyProcessAgent(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string originalGuid, ProxyClient.ReservationService.ProcessAgent agent, string extra) {
            ProxyClient.ReservationService.ModifyProcessAgentRequest inValue = new ProxyClient.ReservationService.ModifyProcessAgentRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.originalGuid = originalGuid;
            inValue.agent = agent;
            inValue.extra = extra;
            ProxyClient.ReservationService.ModifyProcessAgentResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).ModifyProcessAgent(inValue);
            return retVal.ModifyProcessAgentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.RetireProcessAgentResponse ProxyClient.ReservationService.IProcessAgent.RetireProcessAgent(ProxyClient.ReservationService.RetireProcessAgentRequest request) {
            return base.Channel.RetireProcessAgent(request);
        }
        
        public int RetireProcessAgent(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string domainGuid, string serviceGuid, bool state) {
            ProxyClient.ReservationService.RetireProcessAgentRequest inValue = new ProxyClient.ReservationService.RetireProcessAgentRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.domainGuid = domainGuid;
            inValue.serviceGuid = serviceGuid;
            inValue.state = state;
            ProxyClient.ReservationService.RetireProcessAgentResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).RetireProcessAgent(inValue);
            return retVal.RetireProcessAgentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyClient.ReservationService.RegisterResponse ProxyClient.ReservationService.IProcessAgent.Register(ProxyClient.ReservationService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public void Register(ProxyClient.ReservationService.AgentAuthHeader AgentAuthHeader, string registerGuid, ServiceDescription[] info) {
            ProxyClient.ReservationService.RegisterRequest inValue = new ProxyClient.ReservationService.RegisterRequest();
            inValue.AgentAuthHeader = AgentAuthHeader;
            inValue.registerGuid = registerGuid;
            inValue.info = info;
            ProxyClient.ReservationService.RegisterResponse retVal = ((ProxyClient.ReservationService.IProcessAgent)(this)).Register(inValue);
        }
    }
}
