Imports System
Imports System.Data.SqlClient
Imports Microsoft.VisualBasic
Imports WebLabCustomDataTypes

'Copyright (c) 2005 The Massachusetts Institute of Technology. All rights reserved.
'Please see license.txt in top level directory for full license. 

'Author(s): James Hardison (hardison@alum.mit.edu)
'Date: 6/23/2003
'Date Modified: 9/20/2004
'This class provides a VB interface to the WebLab Records Manager methods defined in the Lab server database.  This interface is intended to 
'serve the ASP.NET code that will for the backend of both the Lab Server Administration Site and the Web Services interface that will be exposed
'for use by registered Service Brokers.  To use these methods in your ASP.NET page, first, make sure a compiled copy of this file is present in 
'the /bin directory of your web application.  In your ASP.NET page, import the WebLabDataManagers namespace 
'(<%import namespace="WebLabDataManagers"%>) and, in your code, instantiate a RecordManager object.  From this object, all of the 
'public methods listed below will be accessible.
'
'Dependency List
'Used By:
'   Site Login Page (/login.aspx)
'   Service Broker Notification Script (/notify.aspx)
'   Lab Server Web Services Interface (/services/WebLabServices/LabServerAPI.vb, /bin/WebLabServices.dll)
'   Lab Server Record Manager Library (/bin/RecordManager.dll (this code))
'
'Uses: 
'   WebLab Custom Data Types (/controls/WebLabCustomDataTypes/WebLabCustomDataTypes.vb, /bin/WebLabCustomDataTypes.dll)

Namespace WebLabDataManagers

    Public Class RecordManager

        Dim conWebLabLS As SqlConnection = New SqlConnection("Server=localhost;Database=WebLabServicesLS;Trusted_Connection=True")

        Public Function RetrieveResult(ByVal intBrokerID As Integer, ByVal intBrokerExpID As Integer) As ResultObject
            'This method retrieves the result information associated with the job specified by the Broker ID, Broker Generated Experiment ID pair.
            'The output is of the form of an experiment status code, an experiment result string (XML encoded), any warning messages as well as 
            'fatal errors generated by the experiment.  Specifically, the output will depend on the state of the input experiment code and, 
            'thus, on the value of the experiment status code.  Below is a chart describing the different cases.
            '   experimentStatus = 1    -   job is still in the queue, all other values empty.
            '   experimentStatus = 2    -   job is currently running, all other values empty.
            '   experimetnStatus = 3    -   job terminated normally, experimentResults is populated, warningMessages may be populated.
            '   experimentStatus = 4    -   job terminated with errors, errorMessage is populated, experimentResults may be populated.
            '   experimentStatus = 5    -   job was cancelled by user, all other values empty.
            '   experimentStatus = 6    -   input experiment ID is invalid.


            conWebLabLS.Open()
            Dim strDBQuery As String
            Dim roOutput As ResultObject
            Dim cmdDBQuery As SqlCommand
            Dim dtrDBQuery As SqlDataReader

            strDBQuery = "EXEC rm_RetrieveResultByRemoteID @BrokerID, @ExpID;"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@BrokerID", intBrokerID)
            cmdDBQuery.Parameters.Add("@ExpID", intBrokerExpID)
            dtrDBQuery = cmdDBQuery.ExecuteReader()

            dtrDBQuery.Read()

            roOutput = New ResultObject(CInt(dtrDBQuery("experimentStatus")), dtrDBQuery("experimentResults"), dtrDBQuery("warningMessages"), dtrDBQuery("errorMessages"), dtrDBQuery("labConfig"))

            dtrDBQuery.Close()
            conWebLabLS.Close()

            Return roOutput
        End Function


        Public Function RetrieveResult(ByVal intLocaLExpId As Integer) As ResultObject
            'This method retrieves the result information for the job specified by the Locally Generated Experiment ID.  The output is of the form 
            'of an experiment status code, an experiment result string (XML encoded), any warning messages as well as fatal errors generated by the 
            'experiment.  Specifically, the output will depend on the state of the input experiment code and, thus, on the value of the experiment 
            'status code.  Below is a chart describing the different cases.
            '   experimentStatus = 1    -   job is still in the queue, all other values empty.
            '   experimentStatus = 2    -   job is currently running, all other values empty.
            '   experimetnStatus = 3    -   job terminated normally, experimentResults is populated, warningMessages may be populated.
            '   experimentStatus = 4    -   job terminated with errors, errorMessage is populated, experimentResults may be populated.
            '   experimentStatus = 5    -   job was cancelled by user, all other values empty.
            '   experimentStatus = 6    -   input experiment ID is invalid.

            conWebLabLS.Open()
            Dim strDBQuery As String
            Dim roOutput As ResultObject
            Dim cmdDBQuery As SqlCommand
            Dim dtrDBQuery As SqlDataReader

            strDBQuery = "EXEC rm_RetrieveResultByLocalID @ExpID;"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@ExpID", intLocaLExpId)
            dtrDBQuery = cmdDBQuery.ExecuteReader()

            dtrDBQuery.Read()

            roOutput = New ResultObject(CInt(dtrDBQuery("experimentStatus")), dtrDBQuery("experimentResults"), dtrDBQuery("warningMessages"), dtrDBQuery("errorMessages"), dtrDBQuery("labConfig"))

            dtrDBQuery.Close()
            conWebLabLS.Close()

            Return roOutput
        End Function


        Public Function ExperimentRuntimeEst(ByVal intDataPoints As Integer, ByVal intDeviceProfileID As Integer) As Integer
            'This method calculates an estimate of the time it will take for a given job to execute.  The output of this function is an integer 
            'value representing the estimated time (in seconds) that a submitted job will take to execute.  This estimate is based on the device 
            'that the job is running on and the number of data points being recorded.  This estimate DOES NOT consider the job's wait in the 
            'experiment queue.  This method is intended to be called by a job submission function after the argument experiment specification 
            'has been validated but before it is enqueued. 

            conWebLabLS.Open()
            Dim strDBQuery As String
            Dim cmdDBQuery As SqlCommand
            Dim intOutput As Integer

            strDBQuery = "SELECT dbo.rm_ExpRuntimeEstimate(@Points, @ProfileID);"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@Points", intDataPoints)
            cmdDBQuery.Parameters.Add("@ProfileID", intDeviceProfileID)

            intOutput = cmdDBQuery.ExecuteScalar()

            conWebLabLS.Close()

            Return intOutput
        End Function


        Public Function GetExperimentRecordInfo(ByVal intBrokerID As Integer, ByVal intBrokerExpID As Integer) As ExpRecordInfoObject
            'This method retrieves information on a job specified by Broker ID and a Broker Generated Experiment ID.  The output of this function 
            'is an Experiment Record Information Object containing the public record fields of the specified job.  An invalid expId will result     
            'in an empty return value.
            'Modified 8/31/05 - Bug found in this method such that if a cancelled job's information is called with this method, an error will
            'occur as certain fields that this method assumed were filled in were null.  DBNull checks inserted as remedy. JH
            conWebLabLS.Open()
            Dim strDBQuery, strDeviceName, strUserGroup, strExecTime, strEndTime As String
            Dim intExecElapsed, intJobElapsed As Integer
            Dim eriOutput As ExpRecordInfoObject
            Dim cmdDBQuery As SqlCommand
            Dim dtrDBQuery As SqlDataReader

            strDBQuery = "SELECT user_group, submit_time, exec_time, end_time, exec_elapsed, job_elapsed, device_name FROM dbo.rm_ExpRecordInfoByRemoteID(@BrokerID, @expID);"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@BrokerID", intBrokerID)
            cmdDBQuery.Parameters.Add("@expID", intBrokerExpID)
            dtrDBQuery = cmdDBQuery.ExecuteReader()

            dtrDBQuery.Read()

            If TypeName(dtrDBQuery("device_name")) = "DBNull" Then
                strDeviceName = ""
            Else
                strDeviceName = dtrDBQuery("device_name")
            End If

            If TypeName(dtrDBQuery("user_group")) = "DBNull" Then
                strUserGroup = "NULL"
            Else
                strUserGroup = dtrDBQuery("user_group")
            End If

            If TypeName(dtrDBQuery("exec_time")) = "DBNull" Then
                strExecTime = ""
            Else
                strExecTime = dtrDBQuery("exec_time")
            End If

            If TypeName(dtrDBQuery("end_time")) = "DBNull" Then
                strEndTime = ""
            Else
                strEndTime = dtrDBQuery("end_time")
            End If

            If TypeName(dtrDBQuery("exec_elapsed")) = "DBNull" Then
                intExecElapsed = "0"
            Else
                intExecElapsed = CInt(dtrDBQuery("exec_elapsed"))
            End If

            If TypeName(dtrDBQuery("job_elapsed")) = "DBNull" Then
                intJobElapsed = "0"
            Else
                intJobElapsed = CInt(dtrDBQuery("job_elapsed"))
            End If

            eriOutput = New ExpRecordInfoObject(strUserGroup, dtrDBQuery("submit_time"), strExecTime, strEndTime, intExecElapsed, intJobElapsed, strDeviceName)

            dtrDBQuery.Close()

            conWebLabLS.Close()
            Return eriOutput
        End Function


        Public Function GetExperimentRecordInfo(ByVal intLocalExpID As Integer) As ExpRecordInfoObject
            'This method retrieves information on a job specified by its Locally Generated Experiment ID.  The output of this function 
            'is an Experiment Record Information Object containing the public record fields of the specified job.  An invalid expId 
            'will result in an empty return value
            'Modified 8/31/05 - Bug found in this method such that if a cancelled job's information is called with this method, an error will
            'occur as certain fields that this method assumed were filled in were null.  DBNull checks inserted as remedy. JH
            conWebLabLS.Open()
            Dim strDBQuery, strDeviceName, strUserGroup, strExecTime, strEndTime As String
            Dim intExecElapsed, intJobElapsed As Integer
            Dim eriOutput As ExpRecordInfoObject
            Dim cmdDBQuery As SqlCommand
            Dim dtrDBQuery As SqlDataReader

            strDBQuery = "SELECT user_group, submit_time, exec_time, end_time, exec_elapsed, job_elapsed, device_name FROM dbo.rm_ExpRecordInfoByLocalID(@expID);"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@expID", intLocalExpID)
            dtrDBQuery = cmdDBQuery.ExecuteReader()

            dtrDBQuery.Read()

            If TypeName(dtrDBQuery("device_name")) = "DBNull" Then
                strDeviceName = ""
            Else
                strDeviceName = dtrDBQuery("device_name")
            End If

            If TypeName(dtrDBQuery("user_group")) = "DBNull" Then
                strUserGroup = "NULL"
            Else
                strUserGroup = dtrDBQuery("user_group")
            End If

            If TypeName(dtrDBQuery("exec_time")) = "DBNull" Then
                strExecTime = ""
            Else
                strExecTime = dtrDBQuery("exec_time")
            End If

            If TypeName(dtrDBQuery("end_time")) = "DBNull" Then
                strEndTime = ""
            Else
                strEndTime = dtrDBQuery("end_time")
            End If

            If TypeName(dtrDBQuery("exec_elapsed")) = "DBNull" Then
                intExecElapsed = "0"
            Else
                intExecElapsed = CInt(dtrDBQuery("exec_elapsed"))
            End If

            If TypeName(dtrDBQuery("job_elapsed")) = "DBNull" Then
                intJobElapsed = "0"
            Else
                intJobElapsed = CInt(dtrDBQuery("job_elapsed"))
            End If

            eriOutput = New ExpRecordInfoObject(strUserGroup, dtrDBQuery("submit_time"), strExecTime, strEndTime, intExecElapsed, intJobElapsed, strDeviceName)

            dtrDBQuery.Close()

            conWebLabLS.Close()
            Return eriOutput
        End Function


        Public Function LocalExperimentIDLookup(ByVal intBrokerID As Integer, ByVal intBrokerExpID As Integer) As Integer
            'This method invokes the SQL UDF called rm_ExpIdLookup.  The purpose of this method is to give the caller the ability to retrieve the locally
            'assigned experiment id when the appropriate brokerID/broker assigned experiment id combination is provided.
            conWebLabLS.Open()
            Dim strDBQuery As String
            Dim cmdDBQuery As SqlCommand
            Dim intOutput As Integer

            strDBQuery = "SELECT dbo.rm_ExpIdLookup(@BrokerID, @brokerExpID);"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@BrokerID", intBrokerID)
            cmdDBQuery.Parameters.Add("@brokerExpID", intBrokerExpID)

            intOutput = cmdDBQuery.ExecuteScalar()

            conWebLabLS.Close()

            Return intOutput
        End Function


        Public Function LogSiteLogon(ByVal intUserID As Integer, ByVal strRemoteIP As String, ByVal strUserAgent As String, ByVal blnIsNewLogon As Boolean)
            'This method provides the Lab Server Administration site with a well defined and encapsulated way of logging 
            'site logon events.  intUserID refers to the internal user id associated with the login.  strRemoteIP and 
            'strUserAgent refer to the requestor's IP address and platform signature, respectively.  Finally, blnIsNewLogon
            'catpures whether the login has been performed manually (unauthenticated agent logging in using the username/password
            'fields) or automatically (via previously written cookie).  This method has no return value.
            conWebLabLS.Open()
            Dim strDBQuery, strLoginType As String
            Dim cmdDBQuery As SqlCommand

            If blnIsNewLogon Then
                strLoginType = "MANUAL"
            Else
                strLoginType = "COOKIE"
            End If

            strDBQuery = "INSERT INTO LoginRecord (login_type, user_id, remote_ip, user_agent) VALUES (@LoginType, @UserID, @RemoteIP, @UserAgent);"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@LoginType", strLoginType)
            cmdDBQuery.Parameters.Add("@UserID", intUserID)
            cmdDBQuery.Parameters.Add("@RemoteIP", strRemoteIP)
            cmdDBQuery.Parameters.Add("@UserAgent", strUserAgent)

            cmdDBQuery.ExecuteNonQuery()

            conWebLabLS.Close()
        End Function


        Public Function LogIncomingWebRequest(ByVal intBrokerID As Integer, ByVal strMethodName As String, ByVal blnHasPermission As Boolean, ByVal blnSuccessful As Boolean, ByVal strCompletionStatus As String)
            'This method is a logging mechanism used to trace incoming traffic through the Lab Server Web Service Channel.  The input is the 
            'broker ID used for the method call, the name of the method being called, whether the caller had permission to make the call 
            '(termination based on code completion/error or lack of permission) and a string describing the state of the method at termination.  
            conWebLabLS.Open()
            Dim strDBQuery As String
            Dim cmdDBQuery As SqlCommand

            strDBQuery = "EXEC rm_LogIncomingWebRequest @brokerID, @method, @hasPermission, @success, @status;"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@brokerID", intBrokerID)
            cmdDBQuery.Parameters.Add("@method", strMethodName)
            cmdDBQuery.Parameters.Add("@hasPermission", blnHasPermission)
            cmdDBQuery.Parameters.Add("@success", blnSuccessful)
            cmdDBQuery.Parameters.Add("@status", strCompletionStatus)

            cmdDBQuery.ExecuteNonQuery()
            conWebLabLS.Close()
        End Function

        Public Function LogOutgoingWebRequest(ByVal intBrokerID As Integer, ByVal strMethodName As String, ByVal strDestURL As String, ByVal blnSuccess As Boolean, ByVal strCompletionStatus As String)
            'This method is a logging mechanism used to trace outgoing traffic through the Lab Server Web Service Channel.  The input is the 
            'broker ID of the machine where the method is being called from, the name of the method being called, the URL of that web method 
            'and a string describing the state of the request at termination.  
            conWebLabLS.Open()
            Dim strDBQuery As String
            Dim cmdDBQuery As SqlCommand

            strDBQuery = "EXEC rm_LogOutgoingWebRequest @brokerID, @method, @destURL, @success, @status;"
            cmdDBQuery = New SqlCommand(strDBQuery, conWebLabLS)
            cmdDBQuery.Parameters.Add("@brokerID", intBrokerID)
            cmdDBQuery.Parameters.Add("@method", strMethodName)
            cmdDBQuery.Parameters.Add("@destURL", strDestURL)
            cmdDBQuery.Parameters.Add("@success", blnSuccess)
            cmdDBQuery.Parameters.Add("@status", strCompletionStatus)

            cmdDBQuery.ExecuteNonQuery()
            conWebLabLS.Close()
        End Function

    End Class

End Namespace
