//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace iLabs.Proxies.StruxWare {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataExchange_BP11Binding", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class DataExchangeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetWebServiceInformationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContainerItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlarmEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdatedAlarmEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgeAlarmEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlarmEventTypesOperationCompleted;
        
        /// <remarks/>
        public DataExchangeService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "http://SERVER_REPLACE_ME/EcoStruxure/DataExchange";
        }
        
        /// <remarks/>
        public event GetWebServiceInformationCompletedEventHandler GetWebServiceInformationCompleted;
        
        /// <remarks/>
        public event GetContainerItemsCompletedEventHandler GetContainerItemsCompleted;
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event GetValuesCompletedEventHandler GetValuesCompleted;
        
        /// <remarks/>
        public event SetValuesCompletedEventHandler SetValuesCompleted;
        
        /// <remarks/>
        public event GetHistoryCompletedEventHandler GetHistoryCompleted;
        
        /// <remarks/>
        public event GetAlarmEventsCompletedEventHandler GetAlarmEventsCompleted;
        
        /// <remarks/>
        public event GetUpdatedAlarmEventsCompletedEventHandler GetUpdatedAlarmEventsCompleted;
        
        /// <remarks/>
        public event AcknowledgeAlarmEventsCompletedEventHandler AcknowledgeAlarmEventsCompleted;
        
        /// <remarks/>
        public event GetAlarmEventTypesCompletedEventHandler GetAlarmEventTypesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetWebServiceInform" +
            "ationIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetWebServiceInformationResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetWebServiceInformationResponse GetWebServiceInformation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetWebServiceInformationRequest GetWebServiceInformationRequest) {
            object[] results = this.Invoke("GetWebServiceInformation", new object[] {
                        GetWebServiceInformationRequest});
            return ((GetWebServiceInformationResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWebServiceInformation(GetWebServiceInformationRequest GetWebServiceInformationRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWebServiceInformation", new object[] {
                        GetWebServiceInformationRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetWebServiceInformationResponse EndGetWebServiceInformation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetWebServiceInformationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebServiceInformationAsync(GetWebServiceInformationRequest GetWebServiceInformationRequest) {
            this.GetWebServiceInformationAsync(GetWebServiceInformationRequest, null);
        }
        
        /// <remarks/>
        public void GetWebServiceInformationAsync(GetWebServiceInformationRequest GetWebServiceInformationRequest, object userState) {
            if ((this.GetWebServiceInformationOperationCompleted == null)) {
                this.GetWebServiceInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebServiceInformationOperationCompleted);
            }
            this.InvokeAsync("GetWebServiceInformation", new object[] {
                        GetWebServiceInformationRequest}, this.GetWebServiceInformationOperationCompleted, userState);
        }
        
        private void OnGetWebServiceInformationOperationCompleted(object arg) {
            if ((this.GetWebServiceInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebServiceInformationCompleted(this, new GetWebServiceInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetContainerItemsIn" +
            "", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetContainerItemsResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetContainerItemsResponse GetContainerItems([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetContainerItemsRequest GetContainerItemsRequest) {
            object[] results = this.Invoke("GetContainerItems", new object[] {
                        GetContainerItemsRequest});
            return ((GetContainerItemsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetContainerItems(GetContainerItemsRequest GetContainerItemsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetContainerItems", new object[] {
                        GetContainerItemsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetContainerItemsResponse EndGetContainerItems(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetContainerItemsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetContainerItemsAsync(GetContainerItemsRequest GetContainerItemsRequest) {
            this.GetContainerItemsAsync(GetContainerItemsRequest, null);
        }
        
        /// <remarks/>
        public void GetContainerItemsAsync(GetContainerItemsRequest GetContainerItemsRequest, object userState) {
            if ((this.GetContainerItemsOperationCompleted == null)) {
                this.GetContainerItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContainerItemsOperationCompleted);
            }
            this.InvokeAsync("GetContainerItems", new object[] {
                        GetContainerItemsRequest}, this.GetContainerItemsOperationCompleted, userState);
        }
        
        private void OnGetContainerItemsOperationCompleted(object arg) {
            if ((this.GetContainerItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContainerItemsCompleted(this, new GetContainerItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetItemsIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetItemsResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetItemsResponse GetItems([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetItemsRequest GetItemsRequest) {
            object[] results = this.Invoke("GetItems", new object[] {
                        GetItemsRequest});
            return ((GetItemsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItems(GetItemsRequest GetItemsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItems", new object[] {
                        GetItemsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetItemsResponse EndGetItems(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetItemsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(GetItemsRequest GetItemsRequest) {
            this.GetItemsAsync(GetItemsRequest, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(GetItemsRequest GetItemsRequest, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        GetItemsRequest}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetValuesIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetValuesResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetValuesResponse GetValues([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetValuesRequest GetValuesRequest) {
            object[] results = this.Invoke("GetValues", new object[] {
                        GetValuesRequest});
            return ((GetValuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetValues(GetValuesRequest GetValuesRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetValues", new object[] {
                        GetValuesRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetValuesResponse EndGetValues(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetValuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetValuesAsync(GetValuesRequest GetValuesRequest) {
            this.GetValuesAsync(GetValuesRequest, null);
        }
        
        /// <remarks/>
        public void GetValuesAsync(GetValuesRequest GetValuesRequest, object userState) {
            if ((this.GetValuesOperationCompleted == null)) {
                this.GetValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetValuesOperationCompleted);
            }
            this.InvokeAsync("GetValues", new object[] {
                        GetValuesRequest}, this.GetValuesOperationCompleted, userState);
        }
        
        private void OnGetValuesOperationCompleted(object arg) {
            if ((this.GetValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetValuesCompleted(this, new GetValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/SetValuesIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SetValuesResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public SetValuesResponse SetValues([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] SetValuesRequest SetValuesRequest) {
            object[] results = this.Invoke("SetValues", new object[] {
                        SetValuesRequest});
            return ((SetValuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetValues(SetValuesRequest SetValuesRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetValues", new object[] {
                        SetValuesRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public SetValuesResponse EndSetValues(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SetValuesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetValuesAsync(SetValuesRequest SetValuesRequest) {
            this.SetValuesAsync(SetValuesRequest, null);
        }
        
        /// <remarks/>
        public void SetValuesAsync(SetValuesRequest SetValuesRequest, object userState) {
            if ((this.SetValuesOperationCompleted == null)) {
                this.SetValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetValuesOperationCompleted);
            }
            this.InvokeAsync("SetValues", new object[] {
                        SetValuesRequest}, this.SetValuesOperationCompleted, userState);
        }
        
        private void OnSetValuesOperationCompleted(object arg) {
            if ((this.SetValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetValuesCompleted(this, new SetValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetHistoryIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetHistoryResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetHistoryResponse GetHistory([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetHistoryRequest GetHistoryRequest) {
            object[] results = this.Invoke("GetHistory", new object[] {
                        GetHistoryRequest});
            return ((GetHistoryResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHistory(GetHistoryRequest GetHistoryRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHistory", new object[] {
                        GetHistoryRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetHistoryResponse EndGetHistory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetHistoryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetHistoryAsync(GetHistoryRequest GetHistoryRequest) {
            this.GetHistoryAsync(GetHistoryRequest, null);
        }
        
        /// <remarks/>
        public void GetHistoryAsync(GetHistoryRequest GetHistoryRequest, object userState) {
            if ((this.GetHistoryOperationCompleted == null)) {
                this.GetHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHistoryOperationCompleted);
            }
            this.InvokeAsync("GetHistory", new object[] {
                        GetHistoryRequest}, this.GetHistoryOperationCompleted, userState);
        }
        
        private void OnGetHistoryOperationCompleted(object arg) {
            if ((this.GetHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHistoryCompleted(this, new GetHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetAlarmEventsIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAlarmEventsResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetAlarmEventsResponse GetAlarmEvents([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetAlarmEventsRequest GetAlarmEventsRequest) {
            object[] results = this.Invoke("GetAlarmEvents", new object[] {
                        GetAlarmEventsRequest});
            return ((GetAlarmEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAlarmEvents(GetAlarmEventsRequest GetAlarmEventsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAlarmEvents", new object[] {
                        GetAlarmEventsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetAlarmEventsResponse EndGetAlarmEvents(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetAlarmEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAlarmEventsAsync(GetAlarmEventsRequest GetAlarmEventsRequest) {
            this.GetAlarmEventsAsync(GetAlarmEventsRequest, null);
        }
        
        /// <remarks/>
        public void GetAlarmEventsAsync(GetAlarmEventsRequest GetAlarmEventsRequest, object userState) {
            if ((this.GetAlarmEventsOperationCompleted == null)) {
                this.GetAlarmEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlarmEventsOperationCompleted);
            }
            this.InvokeAsync("GetAlarmEvents", new object[] {
                        GetAlarmEventsRequest}, this.GetAlarmEventsOperationCompleted, userState);
        }
        
        private void OnGetAlarmEventsOperationCompleted(object arg) {
            if ((this.GetAlarmEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlarmEventsCompleted(this, new GetAlarmEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetUpdatedAlarmEven" +
            "tsIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetUpdatedAlarmEventsResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetUpdatedAlarmEventsResponse GetUpdatedAlarmEvents([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetUpdatedAlarmEventsRequest GetUpdatedAlarmEventsRequest) {
            object[] results = this.Invoke("GetUpdatedAlarmEvents", new object[] {
                        GetUpdatedAlarmEventsRequest});
            return ((GetUpdatedAlarmEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUpdatedAlarmEvents(GetUpdatedAlarmEventsRequest GetUpdatedAlarmEventsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUpdatedAlarmEvents", new object[] {
                        GetUpdatedAlarmEventsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetUpdatedAlarmEventsResponse EndGetUpdatedAlarmEvents(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetUpdatedAlarmEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdatedAlarmEventsAsync(GetUpdatedAlarmEventsRequest GetUpdatedAlarmEventsRequest) {
            this.GetUpdatedAlarmEventsAsync(GetUpdatedAlarmEventsRequest, null);
        }
        
        /// <remarks/>
        public void GetUpdatedAlarmEventsAsync(GetUpdatedAlarmEventsRequest GetUpdatedAlarmEventsRequest, object userState) {
            if ((this.GetUpdatedAlarmEventsOperationCompleted == null)) {
                this.GetUpdatedAlarmEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdatedAlarmEventsOperationCompleted);
            }
            this.InvokeAsync("GetUpdatedAlarmEvents", new object[] {
                        GetUpdatedAlarmEventsRequest}, this.GetUpdatedAlarmEventsOperationCompleted, userState);
        }
        
        private void OnGetUpdatedAlarmEventsOperationCompleted(object arg) {
            if ((this.GetUpdatedAlarmEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdatedAlarmEventsCompleted(this, new GetUpdatedAlarmEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/AcknowledgeAlarmEve" +
            "ntsIn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AcknowledgeAlarmEventsResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public AcknowledgeAlarmEventsResponse AcknowledgeAlarmEvents([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] AcknowledgeAlarmEventsRequest AcknowledgeAlarmEventsRequest) {
            object[] results = this.Invoke("AcknowledgeAlarmEvents", new object[] {
                        AcknowledgeAlarmEventsRequest});
            return ((AcknowledgeAlarmEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAcknowledgeAlarmEvents(AcknowledgeAlarmEventsRequest AcknowledgeAlarmEventsRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AcknowledgeAlarmEvents", new object[] {
                        AcknowledgeAlarmEventsRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public AcknowledgeAlarmEventsResponse EndAcknowledgeAlarmEvents(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AcknowledgeAlarmEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AcknowledgeAlarmEventsAsync(AcknowledgeAlarmEventsRequest AcknowledgeAlarmEventsRequest) {
            this.AcknowledgeAlarmEventsAsync(AcknowledgeAlarmEventsRequest, null);
        }
        
        /// <remarks/>
        public void AcknowledgeAlarmEventsAsync(AcknowledgeAlarmEventsRequest AcknowledgeAlarmEventsRequest, object userState) {
            if ((this.AcknowledgeAlarmEventsOperationCompleted == null)) {
                this.AcknowledgeAlarmEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgeAlarmEventsOperationCompleted);
            }
            this.InvokeAsync("AcknowledgeAlarmEvents", new object[] {
                        AcknowledgeAlarmEventsRequest}, this.AcknowledgeAlarmEventsOperationCompleted, userState);
        }
        
        private void OnAcknowledgeAlarmEventsOperationCompleted(object arg) {
            if ((this.AcknowledgeAlarmEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgeAlarmEventsCompleted(this, new AcknowledgeAlarmEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.schneider-electric.com/common/dataexchange/2011/05/GetAlarmEventTypesI" +
            "n", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetAlarmEventTypesResponse", Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
        public GetAlarmEventTypesResponse GetAlarmEventTypes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")] GetAlarmEventTypesRequest GetAlarmEventTypesRequest) {
            object[] results = this.Invoke("GetAlarmEventTypes", new object[] {
                        GetAlarmEventTypesRequest});
            return ((GetAlarmEventTypesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAlarmEventTypes(GetAlarmEventTypesRequest GetAlarmEventTypesRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAlarmEventTypes", new object[] {
                        GetAlarmEventTypesRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public GetAlarmEventTypesResponse EndGetAlarmEventTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GetAlarmEventTypesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAlarmEventTypesAsync(GetAlarmEventTypesRequest GetAlarmEventTypesRequest) {
            this.GetAlarmEventTypesAsync(GetAlarmEventTypesRequest, null);
        }
        
        /// <remarks/>
        public void GetAlarmEventTypesAsync(GetAlarmEventTypesRequest GetAlarmEventTypesRequest, object userState) {
            if ((this.GetAlarmEventTypesOperationCompleted == null)) {
                this.GetAlarmEventTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlarmEventTypesOperationCompleted);
            }
            this.InvokeAsync("GetAlarmEventTypes", new object[] {
                        GetAlarmEventTypesRequest}, this.GetAlarmEventTypesOperationCompleted, userState);
        }
        
        private void OnGetAlarmEventTypesOperationCompleted(object arg) {
            if ((this.GetAlarmEventTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlarmEventTypesCompleted(this, new GetAlarmEventTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetWebServiceInformationRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class AlarmEventsType {
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string SourceID;
        
        /// <remarks/>
        public string SourceName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Acknowledgeable;
        
        /// <remarks/>
        public System.DateTime TimeStampOccurrence;
        
        /// <remarks/>
        public System.DateTime TimeStampTransition;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Priority;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string State;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class AlarmResponseStatusType {
        
        /// <remarks/>
        public bool MoreDataAvailable;
        
        /// <remarks/>
        public string MoreDataRef;
        
        /// <remarks/>
        public string LastUpdate;
        
        /// <remarks/>
        public bool NeedsRefresh;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class HistoryRecordType {
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string State;
        
        /// <remarks/>
        public System.DateTime TimeStamp;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class HistoryRecordsType {
        
        /// <remarks/>
        public string ValueItemId;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HistoryRecord", IsNullable=false)]
        public HistoryRecordType[] List;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class HistoryResponseStatusType {
        
        /// <remarks/>
        public bool MoreDataAvailable;
        
        /// <remarks/>
        public string MoreDataRef;
        
        /// <remarks/>
        public System.DateTime TimeFrom;
        
        /// <remarks/>
        public System.DateTime TimeTo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ResultType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public bool Success;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ValueTypeStateless {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ValueTypeStateful {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string State;
        
        /// <remarks/>
        public string Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ValueItemType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Writeable;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string State;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ArrayOfItemType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ValueItem", IsNullable=false)]
        public ValueItemType[] ValueItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HistoryItem", IsNullable=false)]
        public HistoryItemType[] HistoryItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AlarmItem", IsNullable=false)]
        public AlarmItemType[] AlarmItems;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class HistoryItemType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        public string ValueItemId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class AlarmItemType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string State;
        
        /// <remarks/>
        public string ValueItemId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ErrorResultType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ValueItemTypeBase {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public string Unit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Writeable;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ContainerItemSimpleType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Type;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ContainerItemType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Type;
        
        /// <remarks/>
        public ContainerItemTypeItems Items;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class ContainerItemTypeItems {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ContainerItem", IsNullable=false)]
        public ContainerItemSimpleType[] ContainerItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ValueItem", IsNullable=false)]
        public ValueItemTypeBase[] ValueItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HistoryItem", IsNullable=false)]
        public HistoryItemType[] HistoryItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AlarmItem", IsNullable=false)]
        public AlarmItemType[] AlarmItems;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetWebServiceInformationResponse {
        
        /// <remarks/>
        public GetWebServiceInformationResponseGetWebServiceInformationVersion GetWebServiceInformationVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable=false)]
        public string[] GetWebServiceInformationSupportedOperations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetWebServiceInformationResponseGetWebServiceInformationVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string MajorVersion;
        
        /// <remarks/>
        public string MinorVersion;
        
        /// <remarks/>
        public string UsedNameSpace;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetContainerItemsRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable=false)]
        public string[] GetContainerItemsIds;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetContainerItemsResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ContainerItem", IsNullable=false)]
        public ContainerItemType[] GetContainerItemsItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ErrorResult", IsNullable=false)]
        public ErrorResultType[] GetContainerItemsErrorResults;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetItemsRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable=false)]
        public string[] GetItemsIds;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetItemsResponse {
        
        /// <remarks/>
        public ArrayOfItemType GetItemsItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ErrorResult", IsNullable=false)]
        public ErrorResultType[] GetItemsErrorResults;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetValuesRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable=false)]
        public string[] GetValuesIds;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetValuesResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ValueItem", IsNullable=false)]
        public ValueTypeStateful[] GetValuesItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ErrorResult", IsNullable=false)]
        public ErrorResultType[] GetValuesErrorResults;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class SetValuesRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ValueItem", IsNullable=false)]
        public ValueTypeStateless[] SetValuesItems;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class SetValuesResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Result", IsNullable=false)]
        public ResultType[] SetValuesResults;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetHistoryRequest {
        
        /// <remarks/>
        public GetHistoryRequestGetHistoryParameter GetHistoryParameter;
        
        /// <remarks/>
        public GetHistoryRequestGetHistoryFilter GetHistoryFilter;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetHistoryRequestGetHistoryParameter {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string MoreDataRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetHistoryRequestGetHistoryFilter {
        
        /// <remarks/>
        public System.DateTime TimeFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeFromSpecified;
        
        /// <remarks/>
        public System.DateTime TimeTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeToSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetHistoryResponse {
        
        /// <remarks/>
        public HistoryResponseStatusType GetHistoryResponseStatus;
        
        /// <remarks/>
        public HistoryRecordsType GetHistoryHistoryRecords;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetAlarmEventsRequest {
        
        /// <remarks/>
        public GetAlarmEventsRequestGetAlarmEventsParameter GetAlarmEventsParameter;
        
        /// <remarks/>
        public GetAlarmEventsRequestGetAlarmEventsFilter GetAlarmEventsFilter;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetAlarmEventsRequestGetAlarmEventsParameter {
        
        /// <remarks/>
        public string MoreDataRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetAlarmEventsRequestGetAlarmEventsFilter {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PriorityFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PriorityTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
        public string[] Types;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetAlarmEventsResponse {
        
        /// <remarks/>
        public AlarmResponseStatusType GetAlarmEventsResponseStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AlarmEvent", IsNullable=false)]
        public AlarmEventsType[] GetAlarmEventsAlarmEvents;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetUpdatedAlarmEventsRequest {
        
        /// <remarks/>
        public GetUpdatedAlarmEventsRequestGetUpdatedAlarmEventsParameter GetUpdatedAlarmEventsParameter;
        
        /// <remarks/>
        public GetUpdatedAlarmEventsRequestGetUpdatedAlarmEventsFilter GetUpdatedAlarmEventsFilter;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetUpdatedAlarmEventsRequestGetUpdatedAlarmEventsParameter {
        
        /// <remarks/>
        public string LastUpdate;
        
        /// <remarks/>
        public string MoreDataRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetUpdatedAlarmEventsRequestGetUpdatedAlarmEventsFilter {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PriorityFrom;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PriorityTo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
        public string[] Types;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetUpdatedAlarmEventsResponse {
        
        /// <remarks/>
        public AlarmResponseStatusType GetUpdatedAlarmEventsResponseStatus;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AlarmEvent", IsNullable=false)]
        public AlarmEventsType[] GetUpdatedAlarmEventsAlarmEvents;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class AcknowledgeAlarmEventsRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Id", IsNullable=false)]
        public string[] AcknowledgeAlarmEventsIds;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class AcknowledgeAlarmEventsResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Result", IsNullable=false)]
        public ResultType[] AcknowledgeAlarmEventsResults;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetAlarmEventTypesRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.schneider-electric.com/common/dataexchange/2011/05")]
    public partial class GetAlarmEventTypesResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Type", IsNullable=false)]
        public string[] GetAlarmEventTypesTypes;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetWebServiceInformationCompletedEventHandler(object sender, GetWebServiceInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebServiceInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebServiceInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetWebServiceInformationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetWebServiceInformationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetContainerItemsCompletedEventHandler(object sender, GetContainerItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContainerItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContainerItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetContainerItemsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetContainerItemsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetItemsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetItemsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetValuesCompletedEventHandler(object sender, GetValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetValuesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetValuesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void SetValuesCompletedEventHandler(object sender, SetValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetValuesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetValuesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetHistoryCompletedEventHandler(object sender, GetHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetHistoryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetHistoryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAlarmEventsCompletedEventHandler(object sender, GetAlarmEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlarmEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlarmEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAlarmEventsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAlarmEventsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetUpdatedAlarmEventsCompletedEventHandler(object sender, GetUpdatedAlarmEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdatedAlarmEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdatedAlarmEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUpdatedAlarmEventsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUpdatedAlarmEventsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void AcknowledgeAlarmEventsCompletedEventHandler(object sender, AcknowledgeAlarmEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcknowledgeAlarmEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcknowledgeAlarmEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AcknowledgeAlarmEventsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AcknowledgeAlarmEventsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void GetAlarmEventTypesCompletedEventHandler(object sender, GetAlarmEventTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlarmEventTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlarmEventTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAlarmEventTypesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAlarmEventTypesResponse)(this.results[0]));
            }
        }
    }
}
