wsdl /v /sharetypes /f /n:iLabs.Services /o:.\BatchLSProxy\BatchLSProxy.cs http://localhost/ilabwsdl/I_BLS.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\BatchSBProxy\BatchSBProxy.cs http://localhost/ilabwsdl/I_BatchSB.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\ExperimentStorageProxy\ExperimentStorageProxy.cs http://localhost/ilabwsdl/I_ESS.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\InteractiveLSProxy\InteractiveLSProxy.cs http://localhost/ilabwsdl/I_ILS.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\InteractiveSBProxy\InteractiveSBProxy.cs http://localhost/ilabwsdl/I_ServiceBroker.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\LabSchedulingProxy\LabSchedulingProxy.cs http://localhost/ilabwsdl/I_LSS.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\ProcessAgentProxy\ProcessAgentProxy.cs http://localhost/ilabwsdl/I_ProcessAgent.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\TicketIssuerProxy\TicketIssuerProxy.cs http://localhost/ilabwsdl/I_TicketIssuer.asmx?WSDL
wsdl /v /sharetypes /f /n:iLabs.Services /o:.\UserSchedulingProxy\UserSchedulingProxy.cs http://localhost/ilabwsdl/I_USS.asmx?WSDL