package weblab.client;

// JAVA 1.1 COMPATIBLE

/**
 * Represents an experiment setup connected to an instrument.  A
 * Setup has a setupID, a name, a description, an
 * imageURL, a maximum number of data points that may be generated by
 * any experiment run on this setup, and an ordered list of
 * Terminals.
 *
 * Setup is immutable.
 */
public class Setup
{
  private final int setupID;
  private final String name;
  private final String description;
  private final String imageURL;

  private final Terminal[] terminals;


  /**
   * Constructs a new Setup with the specified values.
   */
  public Setup(int setupID, String name,
		String description, String imageURL,
		Terminal[] terminals)
  {
    this.setupID = setupID;
    this.name = name;
    this.description = description;
    this.imageURL = imageURL;
    
    this.terminals = (Terminal[]) terminals.clone();
  }

  /**
   * Returns the setupID of this.
   */
  public final int getSetupID()
  {
    return setupID;
  }


  /**
   * Returns the name of this setup.
   */
  public final String getName()
  {
    return name;
  }
  
  /**
   * Returns the description of this setup.
   */
  public final String getDescription()
  {
    return description;
  }

  /**
   * Returns a URL pointing to an image of this setup.
   */
  public final String getImageURL()
  {
    return imageURL;
  }

  /**
   * Returns the Terminals of this setup.
   */
  public final Terminal[] getTerminals()
  {
    return (Terminal[]) this.terminals.clone();
  }

  /**
   * Accepts a Visitor, according to the Visitor design pattern.
   */
  public final void accept(Visitor v)
  {
    v.visitSetup(this);
  }

} // end class Device
