package weblab.client;

// JAVA 1.1 COMPLIANT

import java.math.BigDecimal;

/**
 * Represents VAR2, the secondary sweep source.  VAR2Function consists
 * of a start value, a stop value, and a step value.
 *
 * (Note: the scale of VAR2 is always linear and cannot be changed)
 *
 * VAR2Function is immutable.
 */

public class VAR2Function extends SourceFunction
{
  private BigDecimal start;
  private BigDecimal stop;
  private BigDecimal step;

  /**
   * Creates a new VAR2Function with default values.
   */
  public VAR2Function()
  {
    this(BigDecimal.valueOf(0), BigDecimal.valueOf(0),
	 new BigDecimal("0.1"));
  }

  /**
   * Creates a new VAR1Function with the specified values.
   */
  public VAR2Function(BigDecimal start, BigDecimal stop, BigDecimal step)
  {
    this.start = start;
    this.stop = stop;
    this.step = step;
  }

  public final int getType()
  {
    return VAR2_TYPE;
  }

  /**
   * Returns the start value of this.
   */
  public final BigDecimal getStart()
  {
    return this.start;
  }

  /**
   * Returns the stop value of this.
   */
  public final BigDecimal getStop()
  {
    return this.stop;
  }

  /**
   * Returns the step value of this.
   */
  public final BigDecimal getStep()
  {
    return this.step;
  }

  /**
   * Returns the number of data points that will be generated by this
   * function.
   */
  public final int calculatePoints()
  {
    // zero step size -> badness
    if (step.signum() == 0)
      return -1;

    return stop
      .subtract(start)
      .divide(step, 0, BigDecimal.ROUND_FLOOR)
      .intValue()
      + 1;
  }

  // two VAR2Functions are equal if they have equal start, stop, and
  // step values.
  public final boolean equals(Object obj)
  {
    if (obj instanceof VAR2Function)
    {
      VAR2Function f = (VAR2Function) obj;

      return (this.start.compareTo(f.start) == 0 &&
	      this.stop.compareTo(f.stop) == 0 &&
	      this.step.compareTo(f.step) == 0);
    }
    else
      return false;
  }

  /**
   * Accepts a Visitor, according to the Visitor design pattern.
   */
  public final void accept(Visitor v)
  {
    v.visitVAR2Function(this);
  }

} // end class VAR2Function
